settings:
  title: 'Status Page'
  url: 'https://status.theofleck.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: theofleck-com # unique identifier
    name: theofleck.com
    description: 'My resume website' # default=empty
    url: 'https://theofleck.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: plex-theofleck.com
    name: Plex
    description: 'My personal plex server'
    url: 'https://plex.theofleck.com'
    method: GET
    expectStatus: 200

  - id: speedtest-theofleck-com
    name: Speedtest Server
    description: 'Test your connection speed to my server'
    url: 'https://speedtest.theofleck.com'
    method: GET
    expectStatus: 200
    
  - id: bw-theofleck-com
    name: Bitwarden
    description: 'My personal bitwarden server'
    url: 'https://bw.theofleck.com'
    method: GET
    expectStatus: 200
    
  - id: wccpc-hvac
    name: WCCPC HVAC
    url: 'http://76.124.92.26:82'
    method: GET
    expectStatus: 200
    
  - id: wccpc-cameras
    name: WCCPC Cameras
    url: 'http://76.124.92.26:81/doc/page/login.asp'
    method: GET
    expectStatus: 200
