name = "cf-workers-status-page"
workers_dev = false
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
route = "status.theofleck.com/*"
zone_id = "d6a47373d3c974e2349a3b312b8ffda3"

[triggers]
crons = ["*/10 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
